apiVersion: apps/v1
kind: Deployment
metadata:
  name: vehiclesales-deployment
spec:
  selector:
    matchLabels:
      app: vehiclesales
  template:
    metadata:
      labels:
        app: vehiclesales
    spec:
      containers:
      - name: vehiclesales
        image: albersb/vehiclesales:v2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
            - name: MongoDbSettings__Host
              value: mongodb-service
            - name: MongodbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: vehiclesales-secrets
                  key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
        readinessProbe:
            httpGet:
              path: /health/ready
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: vehiclesales-service
spec:
  type: LoadBalancer
  selector:
    app: vehiclesales
  ports:
  - port: 80
    targetPort: 80
